# Site settings
title: Antonio Trento, theme Jeky New Age, the start Bootstrap themplate build for jekyll
email:
description: A jekyll template for landing pages, portfolio and blogging

baseurl: "/newage/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

google_analytics: ""
addthis_id: 
disqus_account: baldoequeiroz

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/baldoequeiroz  
  - title: facebook
    url: https://facebook.com/baldoequeiroz
  - title: google-plus
    url: https://plus.google.com/+baldoequeirozbrasil
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
